import React, { useState } from "react";
import { GrClose } from "react-icons/gr";
import { IoIosArrowRoundForward } from "react-icons/io";
import qrcodeimg from "../assets/qrcodesettingsimg.svg";

const TowFactorAuth = ({ setShowTwoFactor }) => {
  const [menualEntery, setMenualEntery] = useState(false);
  const [scanQRCode, setScanQRCode] = useState(true);
  const toggleModal = () => {
    setShowTwoFactor(false);
  };

  const scanQrCodeHandler = () => {
    setMenualEntery(false);
    setScanQRCode(true);
  };

  const menulyEnterHandler = () => {
    setScanQRCode(false);
    setMenualEntery(true);
  };

  return (
    <div className=" fixed inset-0 flex items-center justify-center z-10">
      <div className=" bg-white rounded-xl   border-2 pl-10 pr-10 md:pb-5 pt-3 shadow-lg">
        <div className="text-center mb-5 flex">
          <h1 className="text-xl lg:text-3xl  font-semibold text-blue-900 md:ml-44">
            Two-Factor Authentication
          </h1>
          <button
            className=" hover:bg-red-300  font-bold text-lg  text-gray-500 rounded-full ml-auto mr-3 w-[30px] h-[30px] pl-1"
            onClick={toggleModal}
          >
            <GrClose />
          </button>
        </div>
        <div className="mb-6 md:text-center font-medium md:font-bold  text-gray-600">
          <p>
            To enhance the security of your account, enable Two-Factor
            Authentication (2FA).
          </p>
          <p>
            With 2FA enabled, you'll need to enter a verification code in
            addition to your password when logging in.
          </p>
        </div>

        <div className="flex justify-between w-[20rem]  md:ml-52 ">
          {scanQRCode ? (
            <button
              onClick={scanQrCodeHandler}
              className="bg-blue-900 text-white border rounded-full px-4 py-2"
            >
              Scan QR Code
            </button>
          ) : (
            <button
              onClick={scanQrCodeHandler}
              className="bg-white text-blue-900 border rounded-full px-4 py-2"
            >
              Scan QR Code
            </button>
          )}
          {/**when clicked Menualy ENter */}
          {menualEntery ? (
            <button
              onClick={menulyEnterHandler}
              className="bg-blue-900 border text-white rounded-full px-4 py-2"
            >
              Manual Entry
            </button>
          ) : (
            <button
              onClick={menulyEnterHandler}
              className="bg-whit border text-blue-900 rounded-full px-4 py-2"
            >
              Manual Entry
            </button>
          )}
        </div>
        {menualEntery ? (
          <div className="flex md:flex-row flex-col md:mt-[5rem]">
            <div
              style={{
                boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
                padding: "20px",
                borderRadius: "15px",
                marginRight: "25px",
              }}
              className=" text-gray-500 font-semibold"
            >
              <h1 className="md:text-2xl">2FA Key:</h1>
              <span className=" text-blue-900 md:text-2xl font-bold">
                XXXX-XXXX-XXXX-XXXX
              </span>
            </div>
            <div className="font-bold text-blue-900">
              <p className="w-[72vw] md:w-[30vw]   md:text-2xl pl-2">
                {" "}
                If you're unable to scan the QR code, you can manually enter the
                following key into your authenticator app
              </p>
            </div>
          </div>
        ) : (
          ""
        )}

        {/**when clicked ScanQrcode */}

        {scanQRCode ? (
          <div className="flex md:flex-row flex-col mt-1 md:mt-[5rem]">
            <div className="ml-20">
              <img className=" w-[8rem] md:w-[15rem] " src={qrcodeimg} alt="" />
            </div>
            <div className="font-bold text-blue-900 ml-12  md:mt-16 ">
              <p className="w-[72vw] md:w-[20vw] text-md  md:text-2xl pl-2 mt-2">
                {" "}
                Scan the QR code with a 2FA authenticator app
              </p>
            </div>
          </div>
        ) : (
          ""
        )}

        <div className=" w-[88vw]md:w-[44vw] h-[1px] bg-gray-500 mt-2 md:mt-10"></div>

        <div className="flex justify-between md:mt-5">
          <div className="text-blue-900">
            <p className="text-sm md:text-xl md:font-semibold ">Once you've set up 2FA,</p>
            <p className="  text-sm md:text-xl  md:font-semibold w-[30vw] ">
              enter the verification code generated by your authenticator app
            </p>
          </div>
          <div className="px-5">
            <div>
              <p className=" border-b-2 border-b-blue-800">
                Enter Verification Code Here
              </p>
            </div>

            <button className="border rounded-full px-2  py-2 mt-2 flex w-[200px]">
              <span>Enable 2FA Button</span>
              <span className="font-blod text-xl mt-1">
                <IoIosArrowRoundForward />
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TowFactorAuth;
